---
title: "package testing"
output: html_document
date: "2023-12-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(devtools)
library(tidyverse)
library(here)
library(summarytools)
library(janitor)
```

```{r}
cocktails <- readRDS(here("code/drinks.rds"))
```

```{r}
view(cocktails %>% dfSummary())
```

Merge:
- Curacao and blue curacao
- irish cream and baileys irish cream
- peachtree schnapps and peach schnapps

Not sure:
- daiquiri mix
- fruit punch
- grenadine
- peach bitters
- pina colada mix
- worcestershire sauce
- zima
```{r}
unique_ing <- unique(colnames(cocktails)) %>% str_trim() %>% sort()

alchohol_vec <- c("151 bacardi rum", "absinthe", "absolut citron", "absolut kurant", "absolut peppar", "absolut vodka", "advocaat", "ale", "amaretto", "anisette", "aperol", "apfelkorn", "apple brandy", "apple cider", "apple schnapps", "applejack", "apricot brandy", "aquavit", "añejo rum", "bacardi limon", "baileys irish cream", "banana liqueur", "beer", "benedictine", "black sambuca", "blackberry brandy", "blended whiskey", "blue curacao", "blueberry schnapps", "bourbon", "brandy", "butterscotch schnapps", "cachaca", "campari", "chambord raspberry liqueur", "champagne", "cherry brandy", "cherry heering", "cherry liqueur","chocolate liqueur", "cider", "coconut liqueur", "coconut rum", "coffee brandy", "coffee liqueur", "cognac", "cointreau", "corona", "cranberry vodka", "cream of coconut", "creme de banane", "creme de cacao", "creme de cassis", "creme de mure", "crown royal", "curacao", "dark creme de cacao", "dark rum","drambuie", "dry vermouth", "dubonnet rouge", "erin cream", "everclear", "firewater", "frangelico", "galliano", "gin", "godiva liqueur", "gold tequila", "goldschlager", "grain alcohol", "grand marnier", "green chartreuse", "green creme de menthe", "guinness stout", "hot damn", "irish cream", "irish whiskey", "jack daniels", "jim beam", "johnnie walker", "jägermeister", "kahlua", "kirschwasser", "kiwi liqueur", "lager", "lemon vodka", "light rum", "lillet blanc", "lime vodka", "malibu rum", "maraschino liqueur", "melon liqueur", "midori melon liqueur", "orange curacao", "ouzo", "peach brandy", "peach schnapps", "peach vodka", "peppermint schnapps", "peychaud bitters", "pisang ambon", "pisco", "port", "prosecco", "raspberry liqueur", "raspberry vodka", "red wine", "ricard", "rum", "rumple minze", "rye whiskey", "sambuca", "scotch", "sherry", "sloe gin", "southern comfort", "spiced rum", "st. germain", "strawberry liqueur", "strawberry schnapps", "sweet vermouth", "tennessee whiskey", "tequila", "tia maria", "triple sec", "vanilla vodka", "vermouth", "vodka", "whiskey", "white creme de menthe", "white rum", "wild turkey", "wine", "yellow chartreuse", "yukon jack")

ingredients_vec <- setdiff(unique_ing, alchohol_vec)
```

# Filtering function
```{r}
cocktails <- cocktails %>% clean_names()
#removing whitespace in colnames
colnames(cocktails) <- colnames(cocktails) %>% str_trim()

filter_list <- function(alcohol = NULL, ing1 =NULL, ing2 = NULL){
  #req(input$alcohol, input$ing1, input$ing2)
  if(!all(c(alcohol, ing1, ing2) %in% colnames(cocktails))){
    stop(cat("Invalid Input"))
  }
  
  if(is.null(alcohol)){
    cat("The base alcohol selection is required")
  }else{
    if(is.null(ing1) && is.null(ing2)){
      df <- cocktails %>%
        dplyr::filter(!is.na(.[[alcohol]]))
    }else if(is.null(ing1) && !is.null(ing2)){
      df <- cocktails %>%
        dplyr::filter(!is.na(.[[alcohol]]), !is.na(.[[ing2]]))
    }else if(!is.null(ing1) && is.null(ing2)){
      df <- cocktails %>%
        dplyr::filter(!is.na(.[[alcohol]]), !is.na(.[[ing1]]))
    }else{
      df <- cocktails %>%
        dplyr::filter(!is.na(.[[alcohol]]), !is.na(.[[ing1]]), !is.na(.[[ing2]]))
    }
  }
  return(df %>% select(Name))# %>% kableExtra::kbl())
}

filter_list(alcohol = "gin")
use_r("show_recipe")
```

# Show recipe function
```{r}
show_recipe <- function(selected){
  df <- cocktails %>% 
      filter(Name == selected)
  
  type <- df$Type
  glass <- df$Glass
  recipe <- df$Recipe
  
  ing_table <- df %>% 
    select(-c(Type, Category, Picture, Glass, Recipe)) %>% 
    pivot_longer(-Name, names_to = "ingredient", values_to = "quantity") %>%
    drop_na() %>%
    select(-Name)
  return(ing_table)
}
show_recipe("gin and tonic")
```
