---
title: "How to Use the Cocktail Selector"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How to Use the Cocktail Selector}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Introduction

This article will guide you through the Cocktail Selector package. You'll learn how to install the package, use its main functions, and explore the various features it offers.

# Installation

Install the Cocktail Selector from GitHub using `devtools`

# Launching the Shiny App

To start the app, load the package "CocktailSelector" and call the "cocktailApp" function

# Navigating the App Interface

The app consists of several tabs, each with specific functionality:

- **Cocktail List Tab**:Select an alcohol type and additional ingredients (max 2 ingredients).View a list of cocktails that can be made with the selected ingredients.Clear selections to start over or be surprised with a random cocktail recommendation.

- **Cocktail Details Tab**: Detailed information about the cocktail is displayed here.Users can view the cocktail's recipe, ingredients, and an image.

- **Information Tab** : Instructions on using the app.

# Using the App

Start by choosing a base alcohol from the dropdown.
Additional ingredient dropdowns will update based on the base alcohol selected.

- **Exploring Recipes**: The app will display drink options based on the selected ingredients. Click on any drink to view detailed information, such as the recipe and ingredients required.

- **Clearing Selections**: At any point, use the 'Clear Ingredients' button to reset your selections and start over.

- **Surprise Me Feature**: Not sure what you want? Use the 'Surprise Me' feature for a random drink selection.

- **Measurement units**: At any point, change the units : international = ml and imperial = oz

# Functions 
You can find the different functions in the reference section 

# Functions 
You can find the different functions in the reference section 
