name: Pkgdown Site

on:
  push:
    branches:
      - package-shiny
  workflow_dispatch:
  
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: package-shiny  # Check out the package-shiny branch
    
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
    
      - name: Install pkgdown and dependencies
        run: |
          install.packages("pkgdown")
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
    
      - name: Build pkgdown Site
        run: pkgdown::build_site()
        shell: Rscript {0}
    
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
