name: Build and Deploy pkgdown Site

on:
  push:
    branches: [main]
    paths:
      - '**.R'
      - '**.md'
      - 'DESCRIPTION'
      - 'vignettes/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install remotes
        run: Rscript -e 'install.packages("remotes")'

      - name: Install pkgdown and dependencies
        run: Rscript -e 'remotes::install_cran("pkgdown"); remotes::install_deps(dependencies = TRUE)'

      - name: Build pkgdown Site
        run: Rscript -e 'pkgdown::build_site()'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
