name: pkgdown 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-pandoc@v2
    - name: Install pkgdown and dependencies
      run: |
        install.packages('pkgdown')
        install.packages('remotes')
        remotes::install_deps(dependencies = TRUE)
      shell: Rscript {0}
    - name: pkgdown 
      run: pkgdown::build_site()
      shell: Rscript {0}
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.1.4
      with:
        branch: gh-pages
        folder: docs
        token: ${{ secrets.GITHUB_TOKEN }}
