name: Pkgdown Site

on:
  push:
    branches:
      - package-shiny
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev libssl-dev
          sudo apt-get install libharfbuzz-dev libfribidi-dev libfreetype6-dev
          sudo apt-get install pandoc  # Install Pandoc

      - name: Install pkgdown and dependencies
        run: |
          options(warn = 2)
          withCallingHandlers({
            install.packages("remotes")
            remotes::install_cran("pkgdown")
            remotes::install_deps(dependencies = TRUE)
          }, warning = function(w) {
            message("Warning: ", w$message)
          }, error = function(e) {
            message("Error: ", e$message)
            stop(e)
          })
        shell: Rscript {0}

      - name: Build pkgdown Site
        run: pkgdown::build_site()
        shell: Rscript {0}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PKGDOWN }}
          publish_branch: main  # Specify the main branch
          publish_dir: ./docs




