name: R-CMD-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-22.04, r: 'release'}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
      - name: Install dependencies
        run: |
          Rscript -e "install.packages('remotes', repos = 'http://cran.rstudio.com')"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: Build package
        run: R CMD build . --no-build-vignettes --no-manual --no-resave-data
        shell: bash
      - name: Check package
        run: R CMD check *tar.gz --no-manual --as-cran
        shell: bash
